# Generated by Django 4.2.1 on 2023-05-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Place Title")),
                (
                    "photo",
                    models.ImageField(upload_to="photos/", verbose_name="Place Photo"),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="Comment"),
                ),
                (
                    "time_create",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Creation Time",
                    ),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Change Time"),
                ),
                ("user_id", models.IntegerField(verbose_name="User ID")),
            ],
            options={
                "verbose_name": "Place",
                "ordering": ["id"],
            },
        ),
    ]
