# Generated by Django 4.2.1 on 2023-05-23 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("placesremember_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User ID",
            ),
        ),
    ]
